package initcmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/darkmintis/Tern/internal/adapter"
	ternerrors "github.com/darkmintis/Tern/internal/errors"
	"github.com/darkmintis/Tern/internal/projectmeta"
)

const ghaWorkflow = `# Generated by tern init — Flutter release with Tern
name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: darkmintis/Tern/action/setup-tern@main
      # Cache fragment also available via: tern cache --github-actions
      - name: Cache Flutter pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: tern-pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            tern-pub-${{ runner.os }}-
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: tern-gradle-${{ runner.os }}-${{ hashFiles('android/**/*.gradle*', 'android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            tern-gradle-${{ runner.os }}-
      - name: Decode Android keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > "$RUNNER_TEMP/upload.jks"
          echo "ANDROID_KEYSTORE=$RUNNER_TEMP/upload.jks" >> "$GITHUB_ENV"
      - run: tern doctor
        env:
          ANDROID_KEYSTORE: ${{ env.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PATH }}
      - run: tern release --dry-run
      # - run: tern release
      # On upload failure without code changes: tern ship last --to play_store
      # Production: tern run release_prod --yes
`

// Result of init.
type Result struct {
	Adapter  string
	Ternfile string
	Workflow string
	Created  []string
	Message  string
}

// Detected project facts used to tailor Ternfile.
type Detected struct {
	Adapter    string
	HasAndroid bool
	HasIOS     bool
	PackageID  string
	BundleID   string
	AppName    string
}

// DetectProject inspects a Flutter (or unknown) project root.
func DetectProject(projectRoot string, reg *adapter.Registry) Detected {
	d := Detected{}
	if reg != nil {
		if ad, ok := reg.Detect(projectRoot); ok {
			d.Adapter = ad.Name()
		}
	}
	if d.Adapter == "" {
		d.Adapter = "unknown"
	}
	if _, err := os.Stat(filepath.Join(projectRoot, "android")); err == nil {
		d.HasAndroid = true
	}
	if _, err := os.Stat(filepath.Join(projectRoot, "ios")); err == nil {
		d.HasIOS = true
	}
	if id, err := projectmeta.AndroidPackageID(projectRoot); err == nil {
		d.PackageID = id
	}
	if id, err := projectmeta.IOSBundleID(projectRoot); err == nil {
		d.BundleID = id
	}
	d.AppName = projectmeta.AppDisplayName(projectRoot)
	return d
}

// RenderTernfile builds a project-shaped Ternfile.
func RenderTernfile(d Detected) string {
	var b strings.Builder
	b.WriteString("# Ternfile — generated by tern init\n")
	fmt.Fprintf(&b, "# Adapter: %s\n", d.Adapter)
	if d.AppName != "" {
		fmt.Fprintf(&b, "# App: %s\n", d.AppName)
	}
	if d.PackageID != "" {
		fmt.Fprintf(&b, "# Android applicationId: %s\n", d.PackageID)
	}
	if d.BundleID != "" {
		fmt.Fprintf(&b, "# iOS bundle id: %s\n", d.BundleID)
	}
	b.WriteString("# Sign before build so android/key.properties exists for release AABs.\n")
	b.WriteString("# Flavors: build android release flavor:prod\n")
	b.WriteString("# Production uploads require --yes (or interactive confirm).\n")
	b.WriteString("# Staged Play rollout: upload … track:production rollout:10\n\n")

	hasA := d.HasAndroid || (!d.HasAndroid && !d.HasIOS)
	hasI := d.HasIOS

	if hasA {
		b.WriteString("lane build:\n")
		b.WriteString("  build android debug\n\n")
		b.WriteString("lane release:\n")
		b.WriteString("  bump version patch\n")
		b.WriteString("  sign android with keystore env:ANDROID_KEYSTORE\n")
		b.WriteString("  build android release\n")
		b.WriteString("  upload android to play_store track:internal release_name:version_build\n")
		b.WriteString("  tag git prefix:v\n\n")
		b.WriteString("# Production (CI: tern run release_prod --yes)\n")
		b.WriteString("lane release_prod:\n")
		b.WriteString("  bump version patch\n")
		b.WriteString("  sign android with keystore env:ANDROID_KEYSTORE\n")
		b.WriteString("  build android release\n")
		b.WriteString("  upload android to play_store track:production rollout:10 release_name:version_build\n")
		b.WriteString("  tag git prefix:v\n\n")
		b.WriteString("lane ship_android:\n")
		b.WriteString("  ship android from last to play_store track:internal\n\n")
	}

	if hasI {
		b.WriteString("lane release_ios:\n")
		b.WriteString("  bump version patch\n")
		b.WriteString("  sign ios with cert env:IOS_CERT\n")
		b.WriteString("  build ios release\n")
		b.WriteString("  upload ios to testflight\n")
		b.WriteString("  tag git prefix:v\n\n")
	}

	if hasA && hasI {
		b.WriteString("lane release_all:\n")
		b.WriteString("  bump version patch\n")
		b.WriteString("  sign android with keystore env:ANDROID_KEYSTORE\n")
		b.WriteString("  sign ios with cert env:IOS_CERT\n")
		b.WriteString("  build android release\n")
		b.WriteString("  build ios release\n")
		b.WriteString("  upload android to play_store track:internal\n")
		b.WriteString("  upload ios to testflight\n")
		b.WriteString("  tag git prefix:v\n")
	}

	return b.String()
}

// Run scaffolds Ternfile and optional GitHub Actions workflow.
func Run(projectRoot string, reg *adapter.Registry, writeWorkflow bool) (Result, error) {
	if projectRoot == "" {
		projectRoot, _ = os.Getwd()
	}
	d := DetectProject(projectRoot, reg)
	res := Result{Adapter: d.Adapter}

	ternPath := filepath.Join(projectRoot, "Ternfile")
	if _, err := os.Stat(ternPath); err == nil {
		return res, ternerrors.New(ternerrors.ClassConfig, "Ternfile already exists")
	}
	body := RenderTernfile(d)
	if err := os.WriteFile(ternPath, []byte(body), 0o644); err != nil {
		return res, ternerrors.Wrap(ternerrors.ClassConfig, "writing Ternfile", err)
	}
	res.Ternfile = ternPath
	res.Created = append(res.Created, ternPath)

	if writeWorkflow {
		wfDir := filepath.Join(projectRoot, ".github", "workflows")
		if err := os.MkdirAll(wfDir, 0o755); err != nil {
			return res, err
		}
		wfPath := filepath.Join(wfDir, "tern-release.yml")
		if _, err := os.Stat(wfPath); err != nil {
			if err := os.WriteFile(wfPath, []byte(ghaWorkflow), 0o644); err != nil {
				return res, err
			}
			res.Workflow = wfPath
			res.Created = append(res.Created, wfPath)
		}
	}

	parts := []string{fmt.Sprintf("initialized Tern for %s", d.Adapter)}
	if d.PackageID != "" {
		parts = append(parts, "package "+d.PackageID)
	}
	if d.HasAndroid && d.HasIOS {
		parts = append(parts, "android+ios lanes")
	} else if d.HasIOS && !d.HasAndroid {
		parts = append(parts, "ios-focused lanes")
	} else {
		parts = append(parts, "android-focused lanes")
	}
	res.Message = strings.Join(parts, " · ")
	return res, nil
}
