package initcmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/darkmintis/Tern/internal/adapter"
	ternerrors "github.com/darkmintis/Tern/internal/errors"
)

// Flutter-focused default Ternfile (v0 supported path).
const ternfileTemplate = `# Ternfile — generated by tern init (Flutter)
# Sign before build so android/key.properties exists for release AABs.

lane build:
  build android debug

lane release:
  bump version patch
  sign android with keystore env:ANDROID_KEYSTORE
  build android release
  upload android to play_store track:internal
  tag git prefix:v

lane release_ios:
  bump version patch
  sign ios with cert env:IOS_CERT
  build ios release
  upload ios to testflight
  tag git prefix:v

lane release_all:
  bump version patch
  sign android with keystore env:ANDROID_KEYSTORE
  sign ios with cert env:IOS_CERT
  build android release
  build ios release
  upload android to play_store track:internal
  upload ios to testflight
  tag git prefix:v

# Retry Play upload without rebuilding (uses .tern/artifacts/android.json)
lane ship_android:
  ship android from last to play_store track:internal
`

const ghaWorkflow = `# Generated by tern init — Flutter release with Tern
name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: darkmintis/Tern/action/setup-tern@main
      # Cache fragment also available via: tern cache --github-actions
      - name: Cache Flutter pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: tern-pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            tern-pub-${{ runner.os }}-
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: tern-gradle-${{ runner.os }}-${{ hashFiles('android/**/*.gradle*', 'android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            tern-gradle-${{ runner.os }}-
      - name: Decode Android keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > "$RUNNER_TEMP/upload.jks"
          echo "ANDROID_KEYSTORE=$RUNNER_TEMP/upload.jks" >> "$GITHUB_ENV"
      - run: tern doctor
        env:
          ANDROID_KEYSTORE: ${{ env.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PATH }}
      - run: tern release --dry-run
      # - run: tern release
      # On upload failure without code changes: tern ship last --to play_store
`

// Result of init.
type Result struct {
	Adapter  string
	Ternfile string
	Workflow string
	Created  []string
	Message  string
}

// Run scaffolds Ternfile and optional GitHub Actions workflow.
func Run(projectRoot string, reg *adapter.Registry, writeWorkflow bool) (Result, error) {
	if projectRoot == "" {
		projectRoot, _ = os.Getwd()
	}
	res := Result{}
	adName := "unknown"
	if reg != nil {
		if ad, ok := reg.Detect(projectRoot); ok {
			adName = ad.Name()
		}
	}
	res.Adapter = adName

	ternPath := filepath.Join(projectRoot, "Ternfile")
	if _, err := os.Stat(ternPath); err == nil {
		return res, ternerrors.New(ternerrors.ClassConfig, "Ternfile already exists")
	}
	if err := os.WriteFile(ternPath, []byte(ternfileTemplate), 0o644); err != nil {
		return res, ternerrors.Wrap(ternerrors.ClassConfig, "writing Ternfile", err)
	}
	res.Ternfile = ternPath
	res.Created = append(res.Created, ternPath)

	if writeWorkflow {
		wfDir := filepath.Join(projectRoot, ".github", "workflows")
		if err := os.MkdirAll(wfDir, 0o755); err != nil {
			return res, err
		}
		wfPath := filepath.Join(wfDir, "tern-release.yml")
		if _, err := os.Stat(wfPath); err != nil {
			if err := os.WriteFile(wfPath, []byte(ghaWorkflow), 0o644); err != nil {
				return res, err
			}
			res.Workflow = wfPath
			res.Created = append(res.Created, wfPath)
		}
	}

	res.Message = fmt.Sprintf("initialized Tern for %s project (Flutter is the v0 supported path)", adName)
	return res, nil
}
