package cache

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GHAFragment is a ready-to-paste GitHub Actions cache section for Flutter releases.
const GHAFragment = `# Generated by: tern cache --github-actions
# Place after checkout / setup-flutter and before tern release.

- name: Cache Flutter pub
  uses: actions/cache@v4
  with:
    path: |
      ~/.pub-cache
      .dart_tool
    key: tern-pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
    restore-keys: |
      tern-pub-${{ runner.os }}-

- name: Cache Gradle
  uses: actions/cache@v4
  with:
    path: |
      ~/.gradle/caches
      ~/.gradle/wrapper
      android/.gradle
    key: tern-gradle-${{ runner.os }}-${{ hashFiles('android/**/*.gradle*', 'android/gradle/wrapper/gradle-wrapper.properties') }}
    restore-keys: |
      tern-gradle-${{ runner.os }}-

# Uncomment on macos runners for iOS:
# - name: Cache CocoaPods
#   uses: actions/cache@v4
#   with:
#     path: |
#       ios/Pods
#       ~/Library/Caches/CocoaPods
#     key: tern-pods-${{ runner.os }}-${{ hashFiles('ios/Podfile.lock') }}
#     restore-keys: |
#       tern-pods-${{ runner.os }}-
`

// WriteGHAFragment writes cache YAML into path (or stdout path "").
func WriteGHAFragment(path string) (string, error) {
	if path == "" || path == "-" {
		return GHAFragment, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(GHAFragment), 0o644); err != nil {
		return "", err
	}
	return fmt.Sprintf("wrote %s", path), nil
}

// Explain returns a short human description of what Tern caches.
func Explain() string {
	return strings.TrimSpace(`Tern Release Engine caching:
- Flutter pub-cache + .dart_tool (keyed by pubspec.lock)
- Gradle caches/wrapper (keyed by gradle files)
- Optional CocoaPods on macOS (keyed by Podfile.lock)

Run: tern cache --github-actions
Or:  tern cache --github-actions -o .github/tern-cache.yml`)
}
